improved error handling

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,6 +24,11 @@ runs:
                VULKAN_SDK_URL=https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/$VULKAN_SDK_FILE
              fi
              wget -q -O $VULKAN_SDK_FILE $VULKAN_SDK_URL
+             if [ test ! -s $VULKAN_SDK_FILE ] ; then
+               echo "Error downloading $VK_VERSION from '$VULKAN_SDK_URL'."
+               exit 2
+             fi
+             $VULKAN_SDK_FILE
              tar -C vulkan_sdk -zxf $VULKAN_SDK_FILE
              VULKAN_SDK=$PWD/$(ls vulkan_sdk/*/x86_64 -d)
              VULKAN_SDK_ROOT=$PWD/vulkan_sdk/`echo $(cd vulkan_sdk && ls)`
@@ -40,6 +45,10 @@ runs:
                VULKAN_SDK_URL=https://sdk.lunarg.com/sdk/download/$VK_VERSION/windows/VulkanSDK-$VK_VERSION-Installer.exe?Human=true
              fi
              curl -s $VULKAN_SDK_URL -o $VULKAN_SDK_FILE
+             if [ test ! -s $VULKAN_SDK_FILE ] ; then
+               echo "Error downloading $VK_VERSION from '$VULKAN_SDK_URL'."
+               exit 2
+             fi
              7z x -aoa ./$VULKAN_SDK_FILE -ovulkan_sdk > nul
              VULKAN_SDK_ROOT=$PWD/vulkan_sdk
              VULKAN_SDK=$PWD/vulkan_sdk
@@ -51,3 +60,9 @@ runs:
         echo "VULKAN_SDK_ROOT=$VULKAN_SDK_ROOT" >> $GITHUB_ENV
         echo "VULKAN_SDK_VERSION=$VULKAN_SDK_VERSION" >> $GITHUB_ENV
         echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
+        if [ test -n "$VULKAN_SDK" ]; then
+          echo "Failed to install Vulkan SDK $VK_VERSION using '$VULKAN_SDK_URL'."
+          exit 3
+        else
+          echo "Vulkan SDK $VK_VERSION ($VULKAN_SDK_VERSION) successfully installed using '$VULKAN_SDK_URL'."
+        fi
