fix github actions deprecation warnings + preflight checks (#12)
* Update action.yml

bump actions/cache to v3

* Update ci.yml

bump actions/checkout to v2.5.0

* bumip actions/checkout to v3

* Windows-only guard on gha-setup-vsdevenv references

* use macos-12 for internal CI tests (avoids macos-latest deprecation warning)

* update readme and SDK reference versions

* multiversion CI tests

* improve error messages for unavailable SDK configs

* check for null sdk_version

* check null sdk another way

* fix exit (return) codes from helper functions

* fix typo

* fix typo

* fix logic typo

* test generation of error annotation

* update cross-platform version list

* Update action.yml

temporarily enable tsmate

* Update action.yml

* Update action_helpers.sh

* update to actions/checkout@v4

* troubleshooting gha-setup-vsdevenv warning

* Update ci.yml

* manual gha-setup-vsdevenv provisioning

* Update ci.yml

* updated SDK reference vers

* trim to representative version list

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,8 +1,8 @@
 name: 'Setup Vulkan SDK'
 description: 'Automatically builds Vulkan SDK components from source.'
 branding:
-  icon: 'play'  
-  color: 'red'  
+  icon: 'play'
+  color: 'red'
 inputs:
   vulkan-config-file:
     description: 'Vulkan SDK configuration path (prefer this to relying on vulkan-query-version lookup)'
@@ -22,13 +22,8 @@ inputs:
     required: false
 runs:
   using: "composite"
-  steps: 
+  steps:
     - uses: humbletim/vsdevenv-shell@e87fcf2359929606ba32db358baef5ede4737aed
-
-    # - name: Setup tmate session
-    #   uses: mxschmitt/action-tmate@v3.9
-    #   with:
-    #     limit-access-to-actor: true
 
     - name: Resolve Vulkan SDK Configuration
       shell: bash
@@ -38,7 +33,8 @@ runs:
         resolve_vulkan_sdk_environment \
           "${{ inputs.vulkan-query-version }}" \
           "${{ inputs.vulkan-config-file }}" \
-          "${{ inputs.vulkan-components }}"
+          "${{ inputs.vulkan-components }}" \
+          || { echo "could not resolve SDK version / JSON configuration $?" ; exit 42 ; }
 
     - name: Configure Development Environment Prerequisites
       shell: bash
@@ -46,8 +42,8 @@ runs:
         # dev prerequisites
         case `uname -s` in
           Darwin) ;;
-          Linux) 
-            sudo apt-get -qq update 
+          Linux)
+            sudo apt-get -qq update
             sudo apt-get -qq install -y libwayland-dev libxrandr-dev
           ;;
           MINGW*) ;;
@@ -59,7 +55,7 @@ runs:
       run: |
         # cache-key.txt
         . $PWD/_vulkan_build/env
-        ( 
+        (
           echo VULKAN_SDK_CONFIG_FILE=$(sha256sum $VULKAN_SDK_CONFIG_FILE || openssl sha256 $VULKAN_SDK_CONFIG_FILE)
           echo VULKAN_SDK_CONFIG_VERSION=$VULKAN_SDK_CONFIG_VERSION
           echo VULKAN_SDK_COMPONENTS=\"$VULKAN_SDK_COMPONENTS\"
@@ -69,7 +65,7 @@ runs:
     - name: Check Vulkan SDK Cache
       id: vulkan-cached-sdk
       if: inputs.vulkan-use-cache != 'false'
-      uses: actions/cache@v2
+      uses: actions/cache@v4
       with:
         path: VULKAN_SDK
         key: ${{ runner.os }}-vulkan-cached-sdk-${{ hashFiles('_vulkan_build/cache-key.txt') }}
@@ -104,7 +100,7 @@ runs:
           -DVULKAN_SDK=${VULKAN_SDK} \
           -DVULKAN_SDK_CONFIG="${VULKAN_SDK_CONFIG_FILE}" \
           -DVULKAN_SDK_COMPONENTS="${VULKAN_SDK_COMPONENTS}" \
-        || { cat _vulkan_build/CMakeFiles/*.log ; exit 4 ; }
+        || { echo "cmake configure failed" >&2 ; cat _vulkan_build/CMakeFiles/*.log ; exit 4 ; }
 
     - name: Build Vulkan SDK Components
       if: steps.vulkan-cached-sdk.outputs.cache-hit != 'true'
