testing cmake build strategy

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,20 +1,21 @@
 name: 'Setup Vulkan SDK'
-description: 'Configures the core Vulkan SDK and sets VULKAN_SDK environment variable.'
+description: 'Configures Vulkan SDK and sets VULKAN_SDK environment variable.'
 branding:
   icon: 'play'  
   color: 'red'  
 inputs:
-  vulkan-version:
-    description: 'Vulkan SDK release version, e.g. 1.2.162.1'
-    default: 'latest'
-    required: false
   vulkan-config-file:
-    description: 'file path to project local SDK spec (will override vulkan-version if both are specified)'
+    description: 'Vulkan SDK configuration path (prefer this to relying on vulkan-remote-version lookup)'
+    default: ''
+    required: true
+  vulkan-remote-version:
+    description: 'Vulkan SDK release version (download configuration file from LunarG web services)'
+    default: ''
     required: false
   vulkan-components:
-    description: 'specify which Vulkan SDK components to install, e.g. headers, loader, glslang'
-    default: headers, loader
-    required: false
+    description: 'specify which Vulkan SDK components to install, e.g. Vulkan-Headers, Vulkan-Loader, Glslang'
+    default: Vulkan-Headers, Vulkan-Loader
+    required: true
   vulkan-use-cache:
     description: 'specify whether to cache VULKAN_SDK/ results between runs (using github actions/cache)'
     default: false
@@ -22,7 +23,17 @@ inputs:
 runs:
   using: "composite"
   steps: 
-    - name: Configure Vulkan Prerequisites
+    - name: Resolve Vulkan SDK Configuration
+      shell: bash
+      run: |
+        . $GITHUB_ACTION_PATH/action_helpers.sh
+        resolve_vulkan_sdk_environment \
+          "${{ inputs.vulkan-remote-url }}" \
+          "${{ inputs.vulkan-remote-version }}" \
+          "${{ inputs.vulkan-config-file }}" \
+          "${{ inputs.vulkan-components }}"
+
+    - name: Configure Development Environment Prerequisites
       shell: bash
       run: |
         case `uname -s` in
@@ -40,42 +51,66 @@ runs:
       uses: actions/cache@v2
       with:
         path: VULKAN_SDK
-        key: ${{ runner.os }}-vulkan-cached-sdk-${{ inputs.vulkan-version }}-${{ hashFiles(inputs.vulkan-config-file) }}-${{ inputs.vulkan-components }}
+        key: ${{ runner.os }}-vulkan-cached-sdk-${{ hashFiles(env.VULKAN_SDK_CONFIG_FILE) }}-${{ inputs.vulkan-components }}
 
-
-    - name: Configure Vulkan SDK
+    - name: Configure Vulkan SDK Build Prerequisites
       if: steps.vulkan-cached-sdk.outputs.cache-hit != 'true'
       shell: bash
       run: |
-        VK_VERSION=${VK_VERSION:-${{ inputs.vulkan-version }}}
-        VK_CONFIG_FILE=${VK_CONFIG_FILE:-${{ inputs.vulkan-config-file }}}
-        VK_COMPONENTS=${VK_COMPONENTS:-${{ inputs.vulkan-components }}}
-        echo "VK_CONFIG_FILE=$VK_CONFIG_FILE" >> $GITHUB_ENV
-        echo "VK_VERSION=$VK_VERSION" >> $GITHUB_ENV
-        echo "VK_COMPONENTS=$VK_COMPONENTS" >> $GITHUB_ENV
-        test -d VULKAN_SDK || mkdir VULKAN_SDK
-        touch VULKAN_SDK/env
-        case `uname -s` in
-          Darwin) ;;
-          Linux) . $GITHUB_ACTION_PATH/prereqs/ubuntu.sh ;;
-          MINGW*) . $GITHUB_ACTION_PATH/prereqs/windows-2021.sh ;;
-        esac
-        if [[ -n "${VK_CONFIG_FILE}" ]] ; then
-          echo "requested SDK config file is $VK_CONFIG_FILE [ $VK_COMPONENTS ]"
-          GITHUB_ENV=VULKAN_SDK/env $GITHUB_ACTION_PATH/install_vulkan_sdk.sh --config "${VK_CONFIG_FILE}" $VK_COMPONENTS
-        else
-          echo "requested SDK version is $VK_VERSION [ $VK_COMPONENTS ]"
-          GITHUB_ENV=VULKAN_SDK/env $GITHUB_ACTION_PATH/install_vulkan_sdk.sh --release $VK_VERSION $VK_COMPONENTS
-        fi
+        . $GITHUB_ACTION_PATH/action_helpers.sh
+        . $PWD/_vulkan_build/env
+        configure_sdk_prereqs $PWD/_vulkan_build/tools
+        echo PATH=$PWD/_vulkan_build/tools/bin:\$PATH >> $PWD/_vulkan_build/env
+        echo "$VULKAN_SDK_BUILD_DIR/env:"
+        echo "--------------------------------------------------------------"
+        cat $VULKAN_SDK_BUILD_DIR/env
+        echo "--------------------------------------------------------------"
 
-    - name: Finalize SDK installation
+    - name: Configure Vulkan SDK Components
+      if: steps.vulkan-cached-sdk.outputs.cache-hit != 'true'
       shell: bash
       run: |
-        . VULKAN_SDK/env
-        cat VULKAN_SDK/env >> $GITHUB_ENV
-        if [ -z "$VULKAN_SDK" ]; then
-          echo "Failed to install Vulkan SDK $VK_VERSION."
-          exit 3
+        . $PWD/_vulkan_build/env
+        cmake -G Ninja -S $GITHUB_ACTION_PATH -B ${VULKAN_SDK_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release \
+          -DVULKAN_SDK=${VULKAN_SDK} \
+          -DVULKAN_SDK_CONFIG="${VULKAN_SDK_CONFIG_FILE}" \
+          -DVULKAN_SDK_COMPONENTS="${VULKAN_SDK_COMPONENTS}"
+
+    - name: Build Vulkan SDK Components
+      if: steps.vulkan-cached-sdk.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        . $PWD/_vulkan_build/env
+        cmake --build ${VULKAN_SDK_BUILD_DIR} --config Release
+
+    - name: Install Vulkan SDK Components
+      if: steps.vulkan-cached-sdk.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        . $PWD/_vulkan_build/env
+        cmake --install ${VULKAN_SDK_BUILD_DIR}
+
+    - name: Verify Vulkan SDK Installation
+      shell: bash
+      run: |
+        . $PWD/_vulkan_build/env
+        test -s ${VULKAN_SDK}/sdk.env
+        . ${VULKAN_SDK}/sdk.env
+        if [[ -d "${VULKAN_SDK}" && -n "${VULKAN_SDK_VERSION}" ]] ; then
+          echo "Vulkan SDK v${VULKAN_SDK_VERSION} successfully installed into ${VULKAN_SDK}."
+          du -hs ${VULKAN_SDK}
         else
-          echo "Vulkan SDK $VK_VERSION ($VULKAN_SDK_VERSION) successfully installed to $VULKAN_SDK."
+          echo "Could not verify Vulkan SDK installation"
+          exit 3
         fi
+
+    - name: Export VULKAN_SDK to GITHUB_ENV
+      shell: bash
+      run: |
+        . $PWD/_vulkan_build/env
+        . ${VULKAN_SDK}/sdk.env
+        (
+          echo VULKAN_SDK=${VULKAN_SDK}
+          echo VULKAN_SDK_VERSION=${VULKAN_SDK_VERSION}
+        ) | tee -a $GITHUB_ENV
+        echo ${VULKAN_SDK}/bin | tee -a $GITHUB_PATH
