[Test] Switch to bash

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -160,20 +160,24 @@ jobs:
         with:
           arch: ${{ github.event.inputs.arch }}
       - name: Test Vulkan SDK Install
-        shell: powershell
+        shell: bash
         run: |
-          echo "Vulkan SDK Version=='$env:VULKAN_SDK_VERSION'"
-          if (!$env:VULKAN_SDK_VERSION) { throw "vulkan sdk install error" }
+          echo "Vulkan SDK Version==$VULKAN_SDK_VERSION"
+          if [[ -z "$VULKAN_SDK_VERSION" ]] ; then
+            echo "vulkan sdk install error"
+            exit 1
+          fi
+
           cd tests
 
           arch=x64
-          if ("${{ inputs.arch }}" -eq "x86"){
+          if [[ ${{ inputs.arch }}==x86 ]] ; then
             arch=Win32
-          }
+          fi
+
           cmake -A $arch -G "Visual Studio 17 2022" -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
           cmake --build build --config release
-          $ENV:PATH="$ENV:PATH;$ENV:VULKAN_SDK/bin"
-          tail -100 build/CMakeFiles/*.log
+          PATH="$PATH:$VULKAN_SDK/bin"
           ./build/test_vulkan
   # 
   setup-macos-with-latest:
